### ISSUE TITLE
diogenes and decorators

### ISSUE THREAD

**Issue by sithmel** [sithmel/diogenes#16]
I had a few thoughts about diogenes API. The trigger for all of them was the use of decorators.

I really think that the decorator pattern fits particularly well in diogenes. You can enhance a service with caching/logging and many different features (just open async-deco and see how many things can be done).
Some of the current features don't fits well if you use this pattern, basically all features relying in introspecting the functions for its name and arity.

So I propose this set of changes:

### remove the feature of using a function in the registry.service method and remove the feature of using an array of functions in the service.dependsOn method

cons
- we lose a shortcut to define a service
- it is not possible using the editor features to jump on a dependency

pros
- we can use decorators without bothering to set or reset the name of the decorated function
- we can easily implement a namespace feature, defining a service with the string "controller:renderpage" and then having the dependency as "renderpage"
- we lose an extra way to perform the same task

### a service can't use callbacks

I used the arity of the function to guess if the service is callback based. But the decorator won't have the same arity. All my decorators for example use "arguments".

cons
I think we might need to define services with callbacks frequently, especially migrating from old code.

pros
it can be fixed easily using promisify (doh another decorator)

As a side note I would like to know what do you think about adding a special feature to define and compose decorators in diogenes.
I was thinking of something like

```js
diogenes
  .service('myservice')
  .provides([cache, promisify, myservice])
  // or .provides(cache, promisify, myservice)
````
equivalent to:
```js
diogenes
  .service('myservice')
  .provides(cache(promisify(myservice)))
````

but it can be just as good doing:

```js

@cache
@promisify
function myservice() {
  ...
}

diogenes
  .service('myservice')
  .provides(myservice)
````
But the decorator specs are still in discussion ....

What's your thoughts @framp @mikeryancodes

**Comment by framp** [comment]
not relying on introspection and dropping callbacks seem like steps forward

```
diogenes
  .service('myservice')
  .provides([cache, promisify, myservice])
```
Looks good.

```
diogenes
  .service('myservice')
  .provides(cache)
  .provides(promisify)
  .provides(myservice)
```
Could be another way

I'm not a fan of es6 decorators as it's just extra syntactic garbage people have to learn - and ends up being the same as functional composition.
 guess optional support shouldn't be much work anyway.

**Comment by mikeryancodes** [comment]
How about:
```javascript
diogenes
  .service('myservice')
  .provides(myservice)
  .decoratedWith(promisify)
  .decoratedWith(cache)
```
or
```javascript
diogenes
  .service('myservice')
  .provides(myservice)
  .decoratedWith([promisify, cache])
```
where the object that's `provide`d needs to be a (possibly decorated) service, and the `decoratedWith` objects each take a service as an argument?

**Comment by sithmel** [comment]
I like more the second proposal from @mikeryancodes : 
```js
diogenes
  .service('myservice')
  .provides(myservice)
  .decoratedWith([promisify, cache])
```
But it has a few problems. 

When should I decorate the function ? when I use "provides"? when I use "decorateWith" ?
A decorated function, being the product of a closure, has a state.
The state is often created when I apply the decoration. For example:
```js
function memoize(func) {
  let oldValue // creating the state here!
  return function () {
    if (oldValue) return oldValue
    oldValue = func()
    return oldValue
  }
}
```
That means I have to create the decorated function BEFORE start using the registry.

Without a better option I would stick to:
```js
registry
  .provides([cache, promisify, myservice])
```

**Comment by sithmel** [comment]
this is now on master. I'll be publishing in the next days
